services:

  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static/:/abcxyz/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy_data:/data/

  chat:
    build:
      dockerfile_inline: |
        FROM python:3-alpine
        RUN pip install websockets pytest-asyncio psycopg2-binary
    command: python -u chat.py
    working_dir: /src/
    volumes:
      - ./src/:/src/
      - .env:/src/.env

  postgres:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - /data/postgres_data/:/var/lib/postgresql/data/
