services:
  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./index.html:/abcxyz/index.html
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy_data:/data/
