services:

  chat:
    build:
      dockerfile_inline: |
        FROM python:3-alpine
        RUN apk add rsvg-convert
        RUN pip install websockets pytest-asyncio
        WORKDIR /app/
        COPY src .
        COPY static/svg/pico.svg pico.svg
    ports:
      - 9754:9754
    command: python3 -u chat.py

  coturn_server:
    image: coturn/coturn:4.5.2
    network_mode: host
