services:

  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static/:/abcxyz/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy_data:/data/

  chat:
    build:
      dockerfile_inline: |
        FROM python:3-alpine
        RUN pip install websockets
    command: python -u chat.py
    volumes:
      - ./src/chat.py:/chat.py
